[package]
name = "iced_audio"
version = "0.7.0"
authors = ["Billy Messenger <https://github.com/BillyDM>"]
license = "MIT"
edition = "2018"
keywords = ["iced", "gui", "audio", "vst", "lv2"]
categories = ["gui", "visualization"]
description = "An extension to the Iced GUI library with useful widgets for audio applications"
homepage = "https://github.com/BillyDM/iced_audio"
documentation = "https://docs.rs/iced_audio"
repository = "https://github.com/BillyDM/iced_audio"
readme = "README.md"

[badges]
maintenance = { status = "actively-developed" }

[workspace]
members = [
    "examples/simple",
    "examples/inputs_tour",
]

# See more keys and their definitions at
# https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
iced = "0.3"

[dependencies]
iced_native = { version = "0.4", path = "../iced/native" }
iced_graphics = { version = "0.2", path = "../iced/graphics", features = ["canvas"] }
